services:
  rmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - 127.0.0.1:15672:15672
      - 127.0.0.1:5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:?required}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:?required}

  kanboard:
    image: kanboard/kanboard
    restart: unless-stopped
    ports:
      - 127.0.0.1:8081:80
    volumes:
      - kanboard-data:/var/www/app/data
      - kanboard-plugins:/var/www/app/plugins
      - kanboard-ssl:/etc/nginx/ssl
    environment:
      PLUGIN_INSTALLER: 'true'
      DB_DRIVER: postgres
      DB_HOSTNAME: postgres
      DB_USERNAME: '${POSTGRES_USER:?required}'
      DB_PASSWORD: '${POSTGRES_PASSWORD:?required}'
      DB_NAME: '${KANBOARD_DB:?required}'

  postgres:
    image: ghcr.io/eternaldeiwos/postgresql:16
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - bot-db-data:/var/lib/postgresql/data
      - ./hack/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      POSTGRES_USER: '${POSTGRES_USER:?required}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:?required}'
      POSTGRES_DB: '${POSTGRES_DB:?required}'
      POSTGRES_SCHEMA: '${POSTGRES_SCHEMA:?required}'

volumes:
  kanboard-data: {}
  kanboard-plugins: {}
  kanboard-ssl: {}
  bot-db-data: {}
