create table "public"."items" (
    "id" integer generated by default as identity not null,
    "codename" text not null,
    "display_name" text not null,
    "faction" text not null,
    "category" text not null,
    "crate_quantity" integer not null,
    "max_crate_stockpile" integer not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."items" enable row level security;

create table "public"."location" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone,
    "iso2" text,
    "iso3" text,
    "slang" text not null default '[]'::text
);


alter table "public"."location" enable row level security;

create table "public"."stockpile" (
    "id" integer generated by default as identity not null,
    "location_id" bigint not null,
    "name" text not null,
    "code" text not null default '00000'::text,
    "guild_sf" bigint not null,
    "role_sf" bigint not null,
    "created_by_sf" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone,
    "war_number" bigint
);


alter table "public"."stockpile" enable row level security;

create table "public"."stockpile-items" (
    "id" integer generated by default as identity not null,
    "item_id" integer not null,
    "stockpile_id" integer not null,
    "quantity" integer,
    "guild_sf" bigint not null,
    "created_by_sf" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "crated" integer
);


alter table "public"."stockpile-items" enable row level security;

create table "public"."stockpile-log" (
    "id" integer generated by default as identity not null,
    "stockpile_id" integer,
    "description" text not null,
    "guild_sf" bigint not null,
    "created_by_sf" bigint not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."stockpile-log" enable row level security;

create table "public"."war" (
    "war_number" bigint not null,
    "winner" smallint not null,
    "started_at" timestamp with time zone not null,
    "ended_at" timestamp with time zone,
    "clapfoot_id" uuid not null
);


alter table "public"."war" enable row level security;

CREATE UNIQUE INDEX items_pkey ON public.items USING btree (id);

CREATE UNIQUE INDEX location_id_key ON public.location USING btree (id);

CREATE UNIQUE INDEX location_pkey ON public.location USING btree (id);

CREATE UNIQUE INDEX "stockpile-items_id_key" ON public."stockpile-items" USING btree (id);

CREATE UNIQUE INDEX "stockpile-items_pkey" ON public."stockpile-items" USING btree (id);

CREATE UNIQUE INDEX "stockpile-log_id_key" ON public."stockpile-log" USING btree (id);

CREATE UNIQUE INDEX "stockpile-log_pkey" ON public."stockpile-log" USING btree (id);

CREATE UNIQUE INDEX stockpile_id_key ON public.stockpile USING btree (id);

CREATE UNIQUE INDEX stockpile_name_key ON public.stockpile USING btree (name);

CREATE UNIQUE INDEX stockpile_pkey ON public.stockpile USING btree (id);

CREATE UNIQUE INDEX war_id_key ON public.war USING btree (war_number);

CREATE UNIQUE INDEX war_pkey ON public.war USING btree (war_number);

alter table "public"."items" add constraint "items_pkey" PRIMARY KEY using index "items_pkey";

alter table "public"."location" add constraint "location_pkey" PRIMARY KEY using index "location_pkey";

alter table "public"."stockpile" add constraint "stockpile_pkey" PRIMARY KEY using index "stockpile_pkey";

alter table "public"."stockpile-items" add constraint "stockpile-items_pkey" PRIMARY KEY using index "stockpile-items_pkey";

alter table "public"."stockpile-log" add constraint "stockpile-log_pkey" PRIMARY KEY using index "stockpile-log_pkey";

alter table "public"."war" add constraint "war_pkey" PRIMARY KEY using index "war_pkey";

alter table "public"."location" add constraint "location_id_key" UNIQUE using index "location_id_key";

alter table "public"."stockpile" add constraint "stockpile_id_key" UNIQUE using index "stockpile_id_key";

alter table "public"."stockpile" add constraint "stockpile_location_id_fkey" FOREIGN KEY (location_id) REFERENCES location(id) not valid;

alter table "public"."stockpile" validate constraint "stockpile_location_id_fkey";

alter table "public"."stockpile" add constraint "stockpile_name_key" UNIQUE using index "stockpile_name_key";

alter table "public"."stockpile" add constraint "stockpile_war_number_fkey" FOREIGN KEY (war_number) REFERENCES war(war_number) not valid;

alter table "public"."stockpile" validate constraint "stockpile_war_number_fkey";

alter table "public"."stockpile-items" add constraint "stockpile-items_id_key" UNIQUE using index "stockpile-items_id_key";

alter table "public"."stockpile-items" add constraint "stockpile-items_item_id_fkey" FOREIGN KEY (item_id) REFERENCES items(id) not valid;

alter table "public"."stockpile-items" validate constraint "stockpile-items_item_id_fkey";

alter table "public"."stockpile-items" add constraint "stockpile-items_stockpile_id_fkey" FOREIGN KEY (stockpile_id) REFERENCES stockpile(id) not valid;

alter table "public"."stockpile-items" validate constraint "stockpile-items_stockpile_id_fkey";

alter table "public"."stockpile-log" add constraint "stockpile-log_id_key" UNIQUE using index "stockpile-log_id_key";

alter table "public"."stockpile-log" add constraint "stockpile-log_stockpile_id_fkey" FOREIGN KEY (stockpile_id) REFERENCES stockpile(id) not valid;

alter table "public"."stockpile-log" validate constraint "stockpile-log_stockpile_id_fkey";

alter table "public"."war" add constraint "war_id_key" UNIQUE using index "war_id_key";

grant delete on table "public"."items" to "anon";

grant insert on table "public"."items" to "anon";

grant references on table "public"."items" to "anon";

grant select on table "public"."items" to "anon";

grant trigger on table "public"."items" to "anon";

grant truncate on table "public"."items" to "anon";

grant update on table "public"."items" to "anon";

grant delete on table "public"."items" to "authenticated";

grant insert on table "public"."items" to "authenticated";

grant references on table "public"."items" to "authenticated";

grant select on table "public"."items" to "authenticated";

grant trigger on table "public"."items" to "authenticated";

grant truncate on table "public"."items" to "authenticated";

grant update on table "public"."items" to "authenticated";

grant delete on table "public"."items" to "service_role";

grant insert on table "public"."items" to "service_role";

grant references on table "public"."items" to "service_role";

grant select on table "public"."items" to "service_role";

grant trigger on table "public"."items" to "service_role";

grant truncate on table "public"."items" to "service_role";

grant update on table "public"."items" to "service_role";

grant delete on table "public"."location" to "anon";

grant insert on table "public"."location" to "anon";

grant references on table "public"."location" to "anon";

grant select on table "public"."location" to "anon";

grant trigger on table "public"."location" to "anon";

grant truncate on table "public"."location" to "anon";

grant update on table "public"."location" to "anon";

grant delete on table "public"."location" to "authenticated";

grant insert on table "public"."location" to "authenticated";

grant references on table "public"."location" to "authenticated";

grant select on table "public"."location" to "authenticated";

grant trigger on table "public"."location" to "authenticated";

grant truncate on table "public"."location" to "authenticated";

grant update on table "public"."location" to "authenticated";

grant delete on table "public"."location" to "service_role";

grant insert on table "public"."location" to "service_role";

grant references on table "public"."location" to "service_role";

grant select on table "public"."location" to "service_role";

grant trigger on table "public"."location" to "service_role";

grant truncate on table "public"."location" to "service_role";

grant update on table "public"."location" to "service_role";

grant delete on table "public"."stockpile" to "anon";

grant insert on table "public"."stockpile" to "anon";

grant references on table "public"."stockpile" to "anon";

grant select on table "public"."stockpile" to "anon";

grant trigger on table "public"."stockpile" to "anon";

grant truncate on table "public"."stockpile" to "anon";

grant update on table "public"."stockpile" to "anon";

grant delete on table "public"."stockpile" to "authenticated";

grant insert on table "public"."stockpile" to "authenticated";

grant references on table "public"."stockpile" to "authenticated";

grant select on table "public"."stockpile" to "authenticated";

grant trigger on table "public"."stockpile" to "authenticated";

grant truncate on table "public"."stockpile" to "authenticated";

grant update on table "public"."stockpile" to "authenticated";

grant delete on table "public"."stockpile" to "service_role";

grant insert on table "public"."stockpile" to "service_role";

grant references on table "public"."stockpile" to "service_role";

grant select on table "public"."stockpile" to "service_role";

grant trigger on table "public"."stockpile" to "service_role";

grant truncate on table "public"."stockpile" to "service_role";

grant update on table "public"."stockpile" to "service_role";

grant delete on table "public"."stockpile-items" to "anon";

grant insert on table "public"."stockpile-items" to "anon";

grant references on table "public"."stockpile-items" to "anon";

grant select on table "public"."stockpile-items" to "anon";

grant trigger on table "public"."stockpile-items" to "anon";

grant truncate on table "public"."stockpile-items" to "anon";

grant update on table "public"."stockpile-items" to "anon";

grant delete on table "public"."stockpile-items" to "authenticated";

grant insert on table "public"."stockpile-items" to "authenticated";

grant references on table "public"."stockpile-items" to "authenticated";

grant select on table "public"."stockpile-items" to "authenticated";

grant trigger on table "public"."stockpile-items" to "authenticated";

grant truncate on table "public"."stockpile-items" to "authenticated";

grant update on table "public"."stockpile-items" to "authenticated";

grant delete on table "public"."stockpile-items" to "service_role";

grant insert on table "public"."stockpile-items" to "service_role";

grant references on table "public"."stockpile-items" to "service_role";

grant select on table "public"."stockpile-items" to "service_role";

grant trigger on table "public"."stockpile-items" to "service_role";

grant truncate on table "public"."stockpile-items" to "service_role";

grant update on table "public"."stockpile-items" to "service_role";

grant delete on table "public"."stockpile-log" to "anon";

grant insert on table "public"."stockpile-log" to "anon";

grant references on table "public"."stockpile-log" to "anon";

grant select on table "public"."stockpile-log" to "anon";

grant trigger on table "public"."stockpile-log" to "anon";

grant truncate on table "public"."stockpile-log" to "anon";

grant update on table "public"."stockpile-log" to "anon";

grant delete on table "public"."stockpile-log" to "authenticated";

grant insert on table "public"."stockpile-log" to "authenticated";

grant references on table "public"."stockpile-log" to "authenticated";

grant select on table "public"."stockpile-log" to "authenticated";

grant trigger on table "public"."stockpile-log" to "authenticated";

grant truncate on table "public"."stockpile-log" to "authenticated";

grant update on table "public"."stockpile-log" to "authenticated";

grant delete on table "public"."stockpile-log" to "service_role";

grant insert on table "public"."stockpile-log" to "service_role";

grant references on table "public"."stockpile-log" to "service_role";

grant select on table "public"."stockpile-log" to "service_role";

grant trigger on table "public"."stockpile-log" to "service_role";

grant truncate on table "public"."stockpile-log" to "service_role";

grant update on table "public"."stockpile-log" to "service_role";

grant delete on table "public"."war" to "anon";

grant insert on table "public"."war" to "anon";

grant references on table "public"."war" to "anon";

grant select on table "public"."war" to "anon";

grant trigger on table "public"."war" to "anon";

grant truncate on table "public"."war" to "anon";

grant update on table "public"."war" to "anon";

grant delete on table "public"."war" to "authenticated";

grant insert on table "public"."war" to "authenticated";

grant references on table "public"."war" to "authenticated";

grant select on table "public"."war" to "authenticated";

grant trigger on table "public"."war" to "authenticated";

grant truncate on table "public"."war" to "authenticated";

grant update on table "public"."war" to "authenticated";

grant delete on table "public"."war" to "service_role";

grant insert on table "public"."war" to "service_role";

grant references on table "public"."war" to "service_role";

grant select on table "public"."war" to "service_role";

grant trigger on table "public"."war" to "service_role";

grant truncate on table "public"."war" to "service_role";

grant update on table "public"."war" to "service_role";


