create table "public"."stockpile-log" (
    "id" integer generated by default as identity not null,
    "stockpile_id" integer,
    "description" text not null,
    "guild_sf" bigint not null,
    "created_by_sf" bigint not null,
    "created_at" timestamp with time zone not null default now()
);

CREATE UNIQUE INDEX "stockpile-log_id_key" ON public."stockpile-log" USING btree (id);

CREATE UNIQUE INDEX "stockpile-log_pkey" ON public."stockpile-log" USING btree (id);

alter table "public"."stockpile-log" add constraint "stockpile-log_pkey" PRIMARY KEY using index "stockpile-log_pkey";

alter table "public"."stockpile-log" add constraint "stockpile-log_id_key" UNIQUE using index "stockpile-log_id_key";

alter table "public"."stockpile-log" add constraint "stockpile-log_stockpile_id_fkey" FOREIGN KEY (stockpile_id) REFERENCES stockpile(id) not valid;

alter table "public"."stockpile-log" validate constraint "stockpile-log_stockpile_id_fkey";


-- Access controls
ALTER TABLE "public"."stockpile-log" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "public"."stockpile-log" TO "anon";

GRANT SELECT ON TABLE "public"."stockpile-log" TO "authenticated";

GRANT DELETE ON TABLE "public"."stockpile-log" TO "service_role";

GRANT INSERT ON TABLE "public"."stockpile-log" TO "service_role";

GRANT REFERENCES ON TABLE "public"."stockpile-log" TO "service_role";

GRANT SELECT ON TABLE "public"."stockpile-log" TO "service_role";

GRANT TRIGGER ON TABLE "public"."stockpile-log" TO "service_role";

GRANT TRUNCATE ON TABLE "public"."stockpile-log" TO "service_role";

GRANT UPDATE ON TABLE "public"."stockpile-log" TO "service_role";