-- Catalog json
-- https://bynnvoniuhrdtkskdcyg.supabase.co/storage/v1/object/public/foxhole-catalog/naval-57-v1/catalog.json
--
-- Create catalog table
DROP TABLE IF EXISTS catalog CASCADE;

CREATE TABLE IF NOT EXISTS
  catalog (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    foxhole_version TEXT NOT NULL,
    catalog_version TEXT NOT NULL,
    code_name TEXT NOT NULL,
    data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    UNIQUE (foxhole_version, catalog_version, code_name)
  );

--
-- Access controls
ALTER TABLE catalog ENABLE ROW LEVEL SECURITY;

GRANT
SELECT
  ON TABLE catalog TO "anon";

GRANT
SELECT
  ON TABLE catalog TO "authenticated";

GRANT DELETE ON TABLE catalog TO "service_role";

GRANT INSERT ON TABLE catalog TO "service_role";

GRANT REFERENCES ON TABLE catalog TO "service_role";

GRANT
SELECT
  ON TABLE catalog TO "service_role";

GRANT TRIGGER ON TABLE catalog TO "service_role";

GRANT
TRUNCATE ON TABLE catalog TO "service_role";

GRANT
UPDATE ON TABLE catalog TO "service_role";

--
-- Function to pull and populate the item catalog from catalog json
-- Catalog is generated by FIR
-- JSON files are available on an attached storage bucket
-- Foxhole version refers to the update; if this changes in patches then running the function again will overwrite those values.
-- Catalog version is an internal version ID to identify breaking changes within a single foxhole version.
-- Versioning is indexed as ${foxhole_version}-${catalog_version} and both can indicate breaking changes
-- Minor and patch versions are omitted.
DROP FUNCTION IF EXISTS populate_catalog CASCADE;

CREATE
OR REPLACE FUNCTION populate_catalog (IN url TEXT, IN foxhole_version TEXT, IN catalog_version TEXT) RETURNS setof catalog AS $$
DECLARE
  r RECORD;
BEGIN

  RETURN QUERY INSERT INTO catalog (foxhole_version, catalog_version, code_name, data)
  SELECT 
    foxhole_version,
    catalog_version,
    (content->>'CodeName')::text code_name,
    content data
  FROM (
    SELECT
      status, 
      jsonb_array_elements(content::jsonb) content
    FROM http_get(url) req
  ) catalog
  ON CONFLICT ON CONSTRAINT catalog_foxhole_version_catalog_version_code_name_key
  DO UPDATE SET (data, created_at) = (EXCLUDED.data, now())
  RETURNING *;

END;
$$ LANGUAGE plpgsql;

--
-- View helper to retrieve the current war
DROP VIEW IF EXISTS catalog_current;

CREATE OR REPLACE VIEW
  catalog_current
WITH
  (security_invoker = on) AS (
    SELECT
      id,
      code_name,
      (data ->> 'DisplayName')::text display_name,
      (
        CASE
          WHEN data ? 'FactionVariant'
          AND (data ->> 'FactionVariant') = 'EFactionId::Wardens' THEN 'WARDENS'::faction
          WHEN data ? 'FactionVariant'
          AND (data ->> 'FactionVariant') = 'EFactionId::Colonials' THEN 'COLONIALS'::faction
          ELSE 'NONE'::faction
        END
      ) faction,
      (
        CASE
          WHEN data ? 'ItemProfileType' THEN (data ->> 'ItemProfileType')::text
          WHEN data ? 'VehicleProfileType' THEN (data ->> 'VehicleProfileType')::text
          WHEN data ? 'ShippableInfo' THEN (data ->> 'ShippableInfo')::text
          WHEN data ->> 'CodeName' IN ('MaterialPlatform') THEN 'EShippableType::Normal'
          ELSE NULL
        END
      ) category,
      (
        CASE
          WHEN data ? 'ItemDynamicData' THEN (data #> '{ItemDynamicData,QuantityPerCrate}')::int
          WHEN data ? 'VehiclesPerCrateBonusQuantity'
          AND data ->> 'VehicleBuildType' IN ('EVehicleBuildType::VehicleFactory', 'EVehicleBuildType::Shipyard') THEN 3 + (data -> 'VehiclesPerCrateBonusQuantity')::int
          WHEN (
            data ? 'VehicleDynamicData'
            AND data ->> 'VehicleBuildType' IN ('EVehicleBuildType::VehicleFactory', 'EVehicleBuildType::Shipyard')
          )
          OR data ->> 'CodeName' IN (
            'Construction',
            'Crane',
            'MaterialPlatform',
            'ConcreteMixer',
            'LiquidContainer',
            'ResourceContainer',
            'ShippingContainer'
          ) THEN 3
          ELSE NULL
        END
      ) crate_quantity,
      (
        CASE
          WHEN data ? 'ItemProfileData' THEN (data #> '{ItemProfileData,ReserveStockpileMaxQuantity}')::int
          -- WHEN
          --   (
          --     data ? 'VehicleDynamicData'
          --       AND data->>'VehicleBuildType' IN ('EVehicleBuildType::NotBuildable','EVehicleBuildType::VehicleFactory','EVehicleBuildType::Shipyard')
          --   ) 
          --   OR data->>'CodeName' IN ('Construction', 'Crane', 'ConcreteMixer', 'LiquidContainer', 'ResourceContainer', 'ShippingContainer') 
          --   THEN 10
          ELSE NULL
        END
      ) stockpile_quantity,
      data
    FROM
      catalog
    WHERE
      foxhole_version = 'naval-57'
      AND catalog_version = 'v1'
  );

-- 
-- Access controls
GRANT
SELECT
  ON TABLE catalog_current TO "anon";

GRANT
SELECT
  ON TABLE catalog_current TO "authenticated";

GRANT
SELECT
  ON TABLE catalog_current TO "service_role";