create table "public"."stockpile" (
    "id" integer generated by default as identity not null,
    "location_id" bigint not null,
    "name" text not null,
    "code" text not null default '00000'::text,
    "guild_sf" bigint not null,
    "role_sf" bigint not null,
    "created_by_sf" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone,
    "war_number" bigint
);


CREATE UNIQUE INDEX stockpile_pkey ON public.stockpile USING btree (id);

alter table "public"."stockpile" add constraint "stockpile_pkey" PRIMARY KEY using index "stockpile_pkey";

alter table "public"."stockpile" add constraint "stockpile_id_key" UNIQUE using index "stockpile_id_key";

alter table "public"."stockpile" add constraint "stockpile_location_id_fkey" FOREIGN KEY (location_id) REFERENCES poi(id) not valid;

alter table "public"."stockpile" validate constraint "stockpile_location_id_fkey";

alter table "public"."stockpile" add constraint "stockpile_war_number_fkey" FOREIGN KEY (war_number) REFERENCES war(war_number) not valid;

alter table "public"."stockpile" validate constraint "stockpile_war_number_fkey";


-- Access controls
ALTER TABLE "public"."stockpile" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "public"."stockpile" TO "anon";

GRANT SELECT ON TABLE "public"."stockpile" TO "authenticated";

GRANT DELETE ON TABLE "public"."stockpile" TO "service_role";

GRANT INSERT ON TABLE "public"."stockpile" TO "service_role";

GRANT REFERENCES ON TABLE "public"."stockpile" TO "service_role";

GRANT SELECT ON TABLE "public"."stockpile" TO "service_role";

GRANT TRIGGER ON TABLE "public"."stockpile" TO "service_role";

GRANT TRUNCATE ON TABLE "public"."stockpile" TO "service_role";

GRANT UPDATE ON TABLE "public"."stockpile" TO "service_role";
