create table "public"."stockpile-items" (
    "id" integer generated by default as identity not null,
    "item_id" integer not null,
    "stockpile_id" integer not null,
    "quantity" integer,
    "guild_sf" bigint not null,
    "created_by_sf" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "crated" integer
);

CREATE UNIQUE INDEX "stockpile-items_pkey" ON public."stockpile-items" USING btree (id);

CREATE UNIQUE INDEX "stockpile-items_id_key" ON public."stockpile-items" USING btree (id);

CREATE UNIQUE INDEX "stockpile-items_pkey" ON public."stockpile-items" USING btree (id);

alter table "public"."stockpile-items" add constraint "stockpile-items_pkey" PRIMARY KEY using index "stockpile-items_pkey";

alter table "public"."stockpile-items" add constraint "stockpile-items_id_key" UNIQUE using index "stockpile-items_id_key";

alter table "public"."stockpile-items" add constraint "stockpile-items_item_id_fkey" FOREIGN KEY (item_id) REFERENCES items(id) not valid;

alter table "public"."stockpile-items" validate constraint "stockpile-items_item_id_fkey";

alter table "public"."stockpile-items" add constraint "stockpile-items_stockpile_id_fkey" FOREIGN KEY (stockpile_id) REFERENCES stockpile(id) not valid;

alter table "public"."stockpile-items" validate constraint "stockpile-items_stockpile_id_fkey";

-- Access controls
ALTER TABLE "public"."items" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "public"."stockpile-items" TO "anon";

GRANT SELECT ON TABLE "public"."stockpile-items" TO "authenticated";

GRANT DELETE ON TABLE "public"."stockpile-items" TO "service_role";

GRANT INSERT ON TABLE "public"."stockpile-items" TO "service_role";

GRANT REFERENCES ON TABLE "public"."stockpile-items" TO "service_role";

GRANT SELECT ON TABLE "public"."stockpile-items" TO "service_role";

GRANT TRIGGER ON TABLE "public"."stockpile-items" TO "service_role";

GRANT TRUNCATE ON TABLE "public"."stockpile-items" TO "service_role";

GRANT UPDATE ON TABLE "public"."stockpile-items" TO "service_role";
