create table "public"."items" (
    "id" integer generated by default as identity not null,
    "codename" text not null,
    "display_name" text not null,
    "faction" text not null,
    "category" text not null,
    "crate_quantity" integer not null,
    "max_crate_stockpile" integer not null,
    "created_at" timestamp with time zone not null default now()
);

CREATE UNIQUE INDEX items_pkey ON public.items USING btree (id);

alter table "public"."items" add constraint "items_pkey" PRIMARY KEY using index "items_pkey";

alter table "public"."items" add constraint "items_pkey" UNIQUE using index "items_pkey";

-- Access controls
ALTER TABLE "public"."items" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "public"."items" TO "anon";

GRANT SELECT ON TABLE "public"."items" TO "authenticated";

GRANT DELETE ON TABLE "public"."items" TO "service_role";

GRANT INSERT ON TABLE "public"."items" TO "service_role";

GRANT REFERENCES ON TABLE "public"."items" TO "service_role";

GRANT SELECT ON TABLE "public"."items" TO "service_role";

GRANT TRIGGER ON TABLE "public"."items" TO "service_role";

GRANT TRUNCATE ON TABLE "public"."items" TO "service_role";

GRANT UPDATE ON TABLE "public"."items" TO "service_role";